HOST: http://api.biblioteca.uoc.edu

--- APILA Learning Resources API ---
---
A RESTful API to manage Learning Resources in context
---

--
Summon
Extension of the Summon API
(http://api.summon.serialssolutions.com/help/api/)
--
Gateway to the Summon API
GET /summon/{?s.cmd,s.debug,s.dym,s.ff,s.fvf,s.fvgf,s.he,s.hs,s.hl,s.ho,s.l,s.mr,s.pn,s.ps,s.role,s.rff,s.rf,s.sort,s.fq,s.q}
/summon/search?s.q=learning+analytics
< 200
< Content-Type: application/json
{ "version": 1,
  "data": "<Summon::Search>{records: 137943, pages: 13795, query_time: 201ms, request_time: 431ms}"
}

Get the documents related to a keyword
GET /summon/documents/{?keyword}
/summon/documents?keyword=learning+analytics
< 200
< Content-Type: application/json
{
    "version": 1,
    "data": {
        "items": [{
            "item": {
                "title": "Learning Analytics",
                "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TYBte11D8EiHibePRaCTRRhSWe4myuDm5hri7KELWhcWXwA5bCEedPwxWAC2UCzeKNHCPCXRyNwsxcIy2cjENNEk1TDFwtzCEth_TjZOsjAAAE16Irw",
                "id": "FETCH-doaj_primary_oai_doaj_articles_2a87da276d89c245a4e1d8789198c3b80",
                "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.genre=article&rft.atitle=Learning+Analytics&rft.jtitle=E-learning+and+Education&rft.au=Erik+Duval&rft.au=Katrien+Verbert&rft.date=2012-06-18&rft.pub=FernUniversit%C3%A4t+Hagen%2C+CampusSource&rft.issn=1860-7470&rft.eissn=1860-7470&rft.volume=1&rft.issue=8&rft.externalDBID=DOA&rft.externalDocID=oai_doaj_articles_2a87da276d89c245a4e1d8789198c3b8",
                "subject_terms": [],
                "authors": [{
                    "fullname": "Erik Duval",
                    "surname": null,
                    "givenname": null,
                    "middlename": null
                }, {
                    "fullname": "Katrien Verbert",
                    "surname": null,
                    "givenname": null,
                    "middlename": null
                }]
            }
        }, {
            "item": {
                "title": "Learning analytics",
                "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TYBte11D8EiHibePRaCTRRgPomhyE2WQcnMNcfbQTUzOjS-AnLUQbwTsbwPrRAMARioTxQ",
                "id": "FETCH-acm_primary_23306350",
                "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Learning+analytics&rft.au=Prinsloo%2C+Paul&rft.au=Slade%2C+Sharon&rft.au=Galpin%2C+Fenella&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=130&rft.epage=133&rft_id=info:doi/10.1145%2F2330601.2330635&rft.externalDocID=2330635",
                "subject_terms": ["University of South Africa (Unisa)", "learning analytics", "student walk", "Thirdspace", "open university (OU)"],
                "authors": [{
                    "fullname": "Prinsloo, Paul",
                    "surname": "Prinsloo",
                    "givenname": "Paul",
                    "middlename": null
                }, {
                    "fullname": "Slade, Sharon",
                    "surname": "Slade",
                    "givenname": "Sharon",
                    "middlename": null
                }, {
                    "fullname": "Galpin, Fenella",
                    "surname": "Galpin",
                    "givenname": "Fenella",
                    "middlename": null
                }]
            }
        }]
    }
}

Get the conferences with more documents related to a keyword
GET /summon/conferences/{?keyword}
/summon/conferences?keyword=learning+analytics
< 200
< Content-Type: application/json
{
    "version": 1,
    "data": {
        "publications": [{
            "publication": {
                "title": "Proceedings of the 2nd International Conference on learning analytics and knowledge",
                "link": "http://uoc.summon.serialssolutions.com/en/search?s.cmd=setHoldingsOnly(false)&t.publicationtitle=Proceedings of the 2nd International Conference on learning analytics and knowledge&fsv=ContentType,learning analytics",
                "count": 15,
                "items": [{
                    "title": "Learning analytics",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmFIZbmbKIOUm2uIs4duYnJufAHkrIV4I2B_G1gnGgAARAQTuw",
                    "id": "FETCH-acm_primary_23306350",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Learning+analytics&rft.au=Prinsloo%2C+Paul&rft.au=Slade%2C+Sharon&rft.au=Galpin%2C+Fenella&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=130&rft.epage=133&rft_id=info:doi/10.1145%2F2330601.2330635&rft.externalDocID=2330635",
                    "subject_terms": ["University of South Africa (Unisa)", "learning analytics", "student walk", "Thirdspace", "open university (OU)"],
                    "authors": [{
                        "fullname": "Prinsloo, Paul",
                        "surname": "Prinsloo",
                        "givenname": "Paul",
                        "middlename": null
                    }, {
                        "fullname": "Slade, Sharon",
                        "surname": "Slade",
                        "givenname": "Sharon",
                        "middlename": null
                    }, {
                        "fullname": "Galpin, Fenella",
                        "surname": "Galpin",
                        "givenname": "Fenella",
                        "middlename": null
                    }]
                }, {
                    "title": "Learning analytics",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmE8iKLJTZRBys01xNlDNzE5N74ActZCvBGwvw1scRsAAEQdE7k",
                    "id": "FETCH-acm_primary_23306050",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Learning+analytics&rft.au=Siemens%2C+George&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=4&rft.epage=8&rft_id=info:doi/10.1145%2F2330601.2330605&rft.externalDocID=2330605",
                    "subject_terms": ["collaboration", "ethics", "practice", "data integration", "learning analytics", "theory", "research"],
                    "authors": [{
                        "fullname": "Siemens, George",
                        "surname": "Siemens",
                        "givenname": "George",
                        "middlename": null
                    }]
                }, {
                    "title": "Social learning analytics",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmE8iCLKTZRBys01xNlDNzE5N74ActZCvBGwv21maGYAAEREE7w",
                    "id": "FETCH-acm_primary_23306160",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Social+learning+analytics&rft.au=Ferguson%2C+Rebecca&rft.au=Shum%2C+Simon&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=23&rft.epage=33&rft_id=info:doi/10.1145%2F2330601.2330616&rft.externalDocID=2330616",
                    "subject_terms": ["social learning analytics", "21 st century skills", "learning analytics", "transferable skills", "social learning", "discourse analytics", "educational assessment", "learning how to learn", "SocialLearn"],
                    "authors": [{
                        "fullname": "Ferguson, Rebecca",
                        "surname": "Ferguson",
                        "givenname": "Rebecca",
                        "middlename": null
                    }, {
                        "fullname": "Shum, Simon",
                        "surname": "Shum",
                        "givenname": "Simon",
                        "middlename": null
                    }]
                }, {
                    "title": "The learning analytics cycle",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmE8iKLKTZRBys01xNlDNzE5N74ActZCvBGwvw060goARGwTvw",
                    "id": "FETCH-acm_primary_23306360",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=The+learning+analytics+cycle&rft.au=Clow%2C+Doug&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=134&rft.epage=138&rft_id=info:doi/10.1145%2F2330601.2330636&rft.externalDocID=2330636",
                    "subject_terms": ["feedback", "academic analytics", "learning analytics", "policy", "analytics"],
                    "authors": [{
                        "fullname": "Clow, Doug",
                        "surname": "Clow",
                        "givenname": "Doug",
                        "middlename": null
                    }]
                }, {
                    "title": "Where learning analytics meets learning design",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmE8iKLMTZRBys01xNlDNzE5N74ActZCvBGwv21mYGkAAETxE8M",
                    "id": "FETCH-acm_primary_23306090",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Where+learning+analytics+meets+learning+design&rft.au=Lockyer%2C+Lori&rft.au=Dawson%2C+Shane&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=14&rft.epage=15&rft_id=info:doi/10.1145%2F2330601.2330609&rft.externalDocID=2330609",
                    "subject_terms": ["pedagogical models", "learning analytics", "university teaching", "learning design", "social network analysis"],
                    "authors": [{
                        "fullname": "Lockyer, Lori",
                        "surname": "Lockyer",
                        "givenname": "Lori",
                        "middlename": null
                    }, {
                        "fullname": "Dawson, Shane",
                        "surname": "Dawson",
                        "givenname": "Shane",
                        "middlename": null
                    }]
                }, {
                    "title": "Learning analytics and higher education",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmE8iCLNTZRBys01xNlDNzE5N74ActZCvBGwvw2s4Q0ARQQTvA",
                    "id": "FETCH-acm_primary_23306100",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Learning+analytics+and+higher+education&rft.au=Slade%2C+Sharon&rft.au=Galpin%2C+Fenella&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=16&rft.epage=17&rft_id=info:doi/10.1145%2F2330601.2330610&rft.externalDocID=2330610",
                    "subject_terms": ["learning analytics", "student walk", "open university (OU)"],
                    "authors": [{
                        "fullname": "Slade, Sharon",
                        "surname": "Slade",
                        "givenname": "Sharon",
                        "middlename": null
                    }, {
                        "fullname": "Galpin, Fenella",
                        "surname": "Galpin",
                        "givenname": "Fenella",
                        "middlename": null
                    }]
                }, {
                    "title": "Learning analytics for collaborative writing",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmHIxZ6bKIOUm2uIs4duYnJufAHksIV4I2Pw3eYGAFWiE-0",
                    "id": "FETCH-acm_primary_23306540",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Learning+analytics+for+collaborative+writing&rft.au=McNely%2C+Brian&rft.au=Gestwicki%2C+Paul&rft.au=Hill%2C+J&rft.au=Parli-Horne%2C+Philip&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=222&rft.epage=225&rft_id=info:doi/10.1145%2F2330601.2330654&rft.externalDocID=2330654",
                    "subject_terms": ["knowledge work", "metacognition", "collaboration", "programming", "distributed work", "learning analytics", "writing"],
                    "authors": [{
                        "fullname": "McNely, Brian",
                        "surname": "McNely",
                        "givenname": "Brian",
                        "middlename": null
                    }, {
                        "fullname": "Gestwicki, Paul",
                        "surname": "Gestwicki",
                        "givenname": "Paul",
                        "middlename": null
                    }, {
                        "fullname": "Hill, J",
                        "surname": "Hill",
                        "givenname": "J",
                        "middlename": null
                    }, {
                        "fullname": "Parli-Horne, Philip",
                        "surname": "Parli-Horne",
                        "givenname": "Philip",
                        "middlename": null
                    }, {
                        "fullname": "Johnson, Erika",
                        "surname": "Johnson",
                        "givenname": "Erika",
                        "middlename": null
                    }]
                }, {
                    "title": "Learning analytics and educational data mining",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmHIq__cRBmk3FxDnD10E5Nz4wsghy3EGwE73MA6xAAAVkkT8A",
                    "id": "FETCH-acm_primary_23306610",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Learning+analytics+and+educational+data+mining&rft.au=Siemens%2C+George&rft.au=Baker%2C+Ryan&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=252&rft.epage=254&rft_id=info:doi/10.1145%2F2330601.2330661&rft.externalDocID=2330661",
                    "subject_terms": ["learning analytics and knowledge", "collaboration", "educational data mining"],
                    "authors": [{
                        "fullname": "Siemens, George",
                        "surname": "Siemens",
                        "givenname": "George",
                        "middlename": null
                    }, {
                        "fullname": "Baker, Ryan",
                        "surname": "Baker",
                        "givenname": "Ryan",
                        "middlename": null
                    }]
                }, {
                    "title": "Educational data mining meets learning analytics",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmHIC6fcRBmk3FxDnD10E5Nz4wsghy3EGwE73KA2LgBWYBPu",
                    "id": "FETCH-acm_primary_23306130",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Educational+data+mining+meets+learning+analytics&rft.au=Baker%2C+Ryan&rft.au=Shum%2C+Simon&rft.au=Duval%2C+Erik&rft.au=Stamper%2C+John&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=20&rft.epage=20&rft_id=info:doi/10.1145%2F2330601.2330613&rft.externalDocID=2330613",
                    "subject_terms": ["data mining", "learning analytics", "education"],
                    "authors": [{
                        "fullname": "Baker, Ryan",
                        "surname": "Baker",
                        "givenname": "Ryan",
                        "middlename": null
                    }, {
                        "fullname": "Shum, Simon",
                        "surname": "Shum",
                        "givenname": "Simon",
                        "middlename": null
                    }, {
                        "fullname": "Duval, Erik",
                        "surname": "Duval",
                        "givenname": "Erik",
                        "middlename": null
                    }, {
                        "fullname": "Stamper, John",
                        "surname": "Stamper",
                        "givenname": "John",
                        "middlename": null
                    }, {
                        "fullname": "Wiley, David",
                        "surname": "Wiley",
                        "givenname": "David",
                        "middlename": null
                    }]
                }, {
                    "title": "Network awareness tool - learning analytics in the workplace",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmHIk45uogxSbq4hzh66icm58QWQwxbijYAdbjNgVAIAVbQT5w",
                    "id": "FETCH-acm_primary_23306200",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Network+awareness+tool+-+learning+analytics+in+the+workplace&rft.au=Bieke%2C+Schreurs&rft.au=Maarten%2C+De&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=59&rft.epage=64&rft_id=info:doi/10.1145%2F2330601.2330620&rft.externalDocID=2330620",
                    "subject_terms": ["informal learning networks", "workplace learning", "networked learning visualizations", "learning analytics", "social network analysis"],
                    "authors": [{
                        "fullname": "Bieke, Schreurs",
                        "surname": "Bieke",
                        "givenname": "Schreurs",
                        "middlename": null
                    }, {
                        "fullname": "Maarten, De",
                        "surname": "Maarten",
                        "givenname": "De",
                        "middlename": null
                    }]
                }, {
                    "title": "Building a data governance model for learning analytics",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmHIY5duogxSbq4hzh66icm58QWQwxbijYAdbmAVYgAAVdsT6w",
                    "id": "FETCH-acm_primary_23306140",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Building+a+data+governance+model+for+learning+analytics&rft.au=Graf%2C+Sabine&rft.au=Ives%2C+Cindy&rft.au=Lockyer%2C+Lori&rft.au=Hobson%2C+Paul&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=21&rft.epage=22&rft_id=info:doi/10.1145%2F2330601.2330614&rft.externalDocID=2330614",
                    "subject_terms": ["ethics", "learning analytics"],
                    "authors": [{
                        "fullname": "Graf, Sabine",
                        "surname": "Graf",
                        "givenname": "Sabine",
                        "middlename": null
                    }, {
                        "fullname": "Ives, Cindy",
                        "surname": "Ives",
                        "givenname": "Cindy",
                        "middlename": null
                    }, {
                        "fullname": "Lockyer, Lori",
                        "surname": "Lockyer",
                        "givenname": "Lori",
                        "middlename": null
                    }, {
                        "fullname": "Hobson, Paul",
                        "surname": "Hobson",
                        "givenname": "Paul",
                        "middlename": null
                    }, {
                        "fullname": "Clow, Doug",
                        "surname": "Clow",
                        "givenname": "Doug",
                        "middlename": null
                    }]
                }, {
                    "title": "1 st International Workshop on Learning Analytics and Linked Data",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmHI5bubKIOUm2uIs4duYnJufAHksIV4I2CH2wyYLgFWIhPv",
                    "id": "FETCH-acm_primary_23306070",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=1+st+International+Workshop+on+Learning+Analytics+and+Linked+Data&rft.au=Drachsler%2C+Hendrik&rft.au=Dietze%2C+Stefan&rft.au=Greller%2C+Wolfgang&rft.au=D%27Aquin%2C+Mathieu&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=9&rft.epage=10&rft_id=info:doi/10.1145%2F2330601.2330607&rft.externalDocID=2330607",
                    "subject_terms": ["educational datasets", "ethics", "privacy", "learning analytics", "linked data"],
                    "authors": [{
                        "fullname": "Drachsler, Hendrik",
                        "surname": "Drachsler",
                        "givenname": "Hendrik",
                        "middlename": null
                    }, {
                        "fullname": "Dietze, Stefan",
                        "surname": "Dietze",
                        "givenname": "Stefan",
                        "middlename": null
                    }, {
                        "fullname": "Greller, Wolfgang",
                        "surname": "Greller",
                        "givenname": "Wolfgang",
                        "middlename": null
                    }, {
                        "fullname": "D'Aquin, Mathieu",
                        "surname": "D'Aquin",
                        "givenname": "Mathieu",
                        "middlename": null
                    }, {
                        "fullname": "Jovanovic, Jelena",
                        "surname": "Jovanovic",
                        "givenname": "Jelena",
                        "middlename": null
                    }, {
                        "fullname": "Pardo, Abelardo",
                        "surname": "Pardo",
                        "givenname": "Abelardo",
                        "middlename": null
                    }, {
                        "fullname": "Reinhardt, Wolfgang",
                        "surname": "Reinhardt",
                        "givenname": "Wolfgang",
                        "middlename": null
                    }, {
                        "fullname": "Verbert, Katrien",
                        "surname": "Verbert",
                        "givenname": "Katrien",
                        "middlename": null
                    }]
                }, {
                    "title": "Learning dispositions and transferable competencies",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmHQYs8YVFa5iTJIubmGOHvoJibnxhdADluINwJ2uM2MLA0AVnET9Q",
                    "id": "FETCH-acm_primary_23306290",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=Learning+dispositions+and+transferable+competencies&rft.au=Shum%2C+Simon&rft.au=Crick%2C+Ruth&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=92&rft.epage=101&rft_id=info:doi/10.1145%2F2330601.2330629&rft.externalDocID=2330629",
                    "subject_terms": ["learning power", "21 st century skills", "learning dispositions", "learning analytics", "effective lifelong learning inventory", "transferable skills", "educational assessment", "learning how to learn"],
                    "authors": [{
                        "fullname": "Shum, Simon",
                        "surname": "Shum",
                        "givenname": "Simon",
                        "middlename": null
                    }, {
                        "fullname": "Crick, Ruth",
                        "surname": "Crick",
                        "givenname": "Ruth",
                        "middlename": null
                    }]
                }, {
                    "title": "GLASS",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmHQYs8YVGa5iTJIubmGOHvoJibnxhdADluINzIGt5ENAFaLE_E",
                    "id": "FETCH-acm_primary_23306420",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=GLASS&rft.au=Leony%2C+Derick&rft.au=Pardo%2C+Abelardo&rft.au=de+la+Fuente+Valent%C3%ADn%2C+Luis&rft.au=de+Castro%2C+David&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=162&rft.epage=163&rft_id=info:doi/10.1145%2F2330601.2330642&rft.externalDocID=2330642",
                    "subject_terms": ["visualization system", "learning analytics", "visualization framework"],
                    "authors": [{
                        "fullname": "Leony, Derick",
                        "surname": "Leony",
                        "givenname": "Derick",
                        "middlename": null
                    }, {
                        "fullname": "Pardo, Abelardo",
                        "surname": "Pardo",
                        "givenname": "Abelardo",
                        "middlename": null
                    }, {
                        "fullname": "de la Fuente Valent\u00edn, Luis",
                        "surname": "de la Fuente Valent\u00edn",
                        "givenname": "Luis",
                        "middlename": null
                    }, {
                        "fullname": "de Castro, David",
                        "surname": "de Castro",
                        "givenname": "David",
                        "middlename": null
                    }, {
                        "fullname": "Kloos, Carlos",
                        "surname": "Kloos",
                        "givenname": "Carlos",
                        "middlename": null
                    }]
                }, {
                    "title": "The learning registry",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE10TSxNTHQNwSMdJt4-FoFOFmHQYs8YVJa5iTJIubmGOHvoJibnxhdADluINzIG3W1uaAAAVvIT9A",
                    "id": "FETCH-acm_primary_23306510",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=proceeding&rft.title=Proceedings+of+the+2nd+International+Conference+on+learning+analytics+and+knowledge&rft.atitle=The+learning+registry&rft.au=Bienkowski%2C+Marie&rft.au=Brecht%2C+John&rft.au=Klo%2C+Jim&rft.series=LAK+%2712&rft.date=2012-04-29&rft.pub=ACM&rft.isbn=9781450311113&rft.spage=208&rft.epage=211&rft_id=info:doi/10.1145%2F2330601.2330651&rft.externalDocID=2330651",
                    "subject_terms": ["social metadata", "attention metadata", "learning-resource analytics", "learning analytics"],
                    "authors": [{
                        "fullname": "Bienkowski, Marie",
                        "surname": "Bienkowski",
                        "givenname": "Marie",
                        "middlename": null
                    }, {
                        "fullname": "Brecht, John",
                        "surname": "Brecht",
                        "givenname": "John",
                        "middlename": null
                    }, {
                        "fullname": "Klo, Jim",
                        "surname": "Klo",
                        "givenname": "Jim",
                        "middlename": null
                    }]
                }]
            }
        }]
    }
}

Get the journals with more documents related to a keyword
GET /summon/journals/{?keyword}
/summon/journals?keyword=learning+analytics
< 200
< Content-Type: application/json
{
    "version": 1,
    "data": {
        "publications": [{
            "publication": {
                "title": "Educational Technology & Society",
                "link": "http://uoc.summon.serialssolutions.com/en/search?s.cmd=setHoldingsOnly(false)&t.publicationtitle=Educational Technology & Society&fsv=ContentType,learning analytics",
                "count": 5,
                "items": [{
                    "title": "Social Learning Analytics",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE1Al5mZ6xqCRzpMvH0sAp0swngQRZSbKEOom2uIs4cu9BYA3VRQb0Q3ydAo0Tg5JckiMckkORVYX5sDezBGaYkWRsamlimp5slpwDYBsH9okGiSapqWbGJuZmoMuu3AMNE4zdAQaAYAcFoiig",
                    "id": "FETCH-LOGICAL-e1022-b12a3cdb8ab4ce05674462fa82359de7cf324eb20a4e5fc4765353201a3f11e10",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.genre=article&rft.atitle=Social+Learning+Analytics&rft.jtitle=Journal+of+Educational+Technology+%26+Society&rft.au=Simon+Buckingham+Shum&rft.au=Rebecca+Ferguson&rft.date=2012&rft.pub=International+Forum+of+Educational+Technology+%26+Society&rft.issn=1176-3647&rft.volume=15&rft.issue=3&rft.spage=3&rft.externalDocID=2890472441",
                    "subject_terms": ["Online education", "Informal Learning", "Social networks", "Social learning", "Dispositions", "Learning Analytics", "Discourse", "Social Networks", "Research", "Social Learning", "Usage"],
                    "authors": [{
                        "fullname": "Buckingham Shum, Simon",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }, {
                        "fullname": "Ferguson, Rebecca",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }]
                }, {
                    "title": "Translating Learning into Numbers: A Generic Framework for Learning Analytics",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE1Al5mZ6xqCRzpMvH0sAp0swpA3yLiJMoS6uYY4e-hCrwHQTQXWfkBt5olJFuaJBonGhkZAC5NSzEySjUxSDJJSLFKAmdPQxNAkxcQsMSXZBEinGSdaWADrOMtUk0RzA9MUC6BCAKEaI4k",
                    "id": "FETCH-LOGICAL-e1024-47ab87a0a312eccbd64c24d0bd8ddde1414d46adc44d4f3a889019e4a705d84d0",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.genre=article&rft.atitle=Translating+Learning+into+Numbers%3A+A+Generic+Framework+for+Learning+Analytics&rft.jtitle=Educational+Technology+%26+Society&rft.au=Greller%2C+Wolfgang&rft.au=Drachsler%2C+Hendrik&rft.date=2012&rft.pub=International+Forum+of+Educational+Technology+%26+Society&rft.issn=1436-4522&rft.volume=15&rft.issue=3&rft.spage=42&rft.epage=57&rft.externalDocID=EJ992502",
                    "subject_terms": ["Data for learning", "Learning", "Data mining", "Teachers, Rating of", "Educational data mining", "Methods", "Ethics", "Educational evaluation", "Learning analytics", "Framework", "Research", "Domain design"],
                    "authors": [{
                        "fullname": "Greller, Wolfgang",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }, {
                        "fullname": "Drachsler, Hendrik",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }]
                }, {
                    "title": "Design and Implementation of a Learning Analytics Toolkit for Teachers",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE1Al5mZ6xqCRzpMvH0sAp0swpAXTrmJMoS6uYY4e-hCrwHQTTUEXbZqZphkkGRsZpxqnmKamGRqZJKaZpBkZJYMOmsuFSgEbJMnG6VYpFkAy-I0M2OzNIPE1BSjVJMkM-O0FANTAwMAgrAjAA",
                    "id": "FETCH-LOGICAL-e1025-61b0b363e7d5ab524ef0b26c3714ed5a862c2d8f8362f636f0aed2e4b63fd0500",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.genre=article&rft.atitle=Design+and+Implementation+of+a+Learning+Analytics+Toolkit+for+Teachers&rft.jtitle=Journal+of+Educational+Technology+%26+Society&rft.au=Anna+Lea+Dyckhoff&rft.au=Dennis+Zielke&rft.au=Mareike+B%C3%BCltmann&rft.au=Mohamed+Amine+Chatti&rft.date=2012&rft.pub=International+Forum+of+Educational+Technology+%26+Society&rft.issn=1176-3647&rft.volume=15&rft.issue=3&rft.spage=58&rft.externalDocID=2890472431",
                    "subject_terms": ["Academic achievement", "Teacher support", "Electronic data processing", "Technology application", "Methods", "Information management", "Improving educational software", "Learning management systems", "Practice", "Usage", "EDM", "Learning analytics", "Teachers", "Research", "Educational software"],
                    "authors": [{
                        "fullname": "Dyckhoff, Anna Lea",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }, {
                        "fullname": "Zielke, Dennis",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }, {
                        "fullname": "Bultmann, Mareike",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }, {
                        "fullname": "Chatti, Mohamed Amine",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }, {
                        "fullname": "Schroeder, Ulrik",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }]
                }, {
                    "title": "Dataset-Driven Research to Support Learning and Knowledge Analytics",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwY2CQQysPnANCfYzMTE1Al5mZ6xqCRzpMvH0sAp0swpCbgm6iDKFuriHOHrrQawB0Uw1BnRvLNNBckWWSSZJZsmWaoZlFSlqKObBaSU5JMU6xSEk2TTYHZttE0IRbYoqxmUUSsBJKSwMdomKUnGKZmGIAAIeDIzA",
                    "id": "FETCH-LOGICAL-e1020-9f68429b4b6c9f168dfd7661cdd3d8dc5c7153a3891ad368b381ff19582cd9ad0",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.genre=article&rft.atitle=Dataset-Driven+Research+to+Support+Learning+and+Knowledge+Analytics&rft.jtitle=Educational+Technology+%26+Society&rft.au=Verbert%2C+Katrien&rft.au=Manouselis%2C+Nikos&rft.au=Drachsler%2C+Hendrik&rft.au=Duval%2C+Erik&rft.date=2012&rft.pub=International+Forum+of+Educational+Technology+%26+Society&rft.issn=1436-4522&rft.volume=15&rft.issue=3&rft.spage=133&rft.epage=148&rft.externalDocID=EJ992519",
                    "subject_terms": ["Electronic data processing", "Educational technology", "Methods", "Datasets", "Learning and knowledge analytics", "Educational evaluation", "Algorithms", "Open science", "Research"],
                    "authors": [{
                        "fullname": "Verbert, Katrien",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }, {
                        "fullname": "Manouselis, Nikos",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }, {
                        "fullname": "Drachsler, Hendrik",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }, {
                        "fullname": "Duval, Erik",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }]
                }, {
                    "title": "Numbers Are Not Enough. Why e-Learning Analytics Failed to Inform an Institutional Strategic Plan",
                    "link": "http://uoc.summon.serialssolutions.com/link/0/eLvHCXMwXZ0xDoAgDEW5hKs3IBEBpatEY6KDJure1nL_IwjGyUu8_9s_PKXqHw_idq5t512RmfXavJ8Ot6xhH8L1Yc8W7E2VOqfxiLP-NABaindau-4GkNwEg5jU50RzWPZAS2gFiRqWNtcez5CQgQQkn0ScgMgbRuK7eQB9siPD",
                    "id": "FETCH-LOGICAL-e1021-46d99e8828e1f77824a02803ba3eabb0ce20805c9fac9be9e402cf9bb51cabcd0",
                    "open_url": "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info:sid/summon.serialssolutions.com&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.genre=article&rft.atitle=Numbers+Are+Not+Enough.+Why+e-Learning+Analytics+Failed+to+Inform+an+Institutional+Strategic+Plan&rft.jtitle=Journal+of+Educational+Technology+%26+Society&rft.au=Leah+P+Macfadyen&rft.au=Shane+Dawson&rft.date=2012&rft.pub=International+Forum+of+Educational+Technology+%26+Society&rft.issn=1176-3647&rft.volume=15&rft.issue=3&rft.spage=149&rft.externalDocID=2890472471",
                    "subject_terms": ["Online education", "Methods", "Learning management systems", "Institutional culture", "Learning management system (LMS)", "Virtual learning environment (VLE)", "Strategic planning", "Student engagement", "Learning analytics", "Visualization (Computers)", "Educational planning", "Research", "Change management"],
                    "authors": [{
                        "fullname": "Macfadyen, Leah P",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }, {
                        "fullname": "Dawson, Shane",
                        "surname": null,
                        "givenname": null,
                        "middlename": null
                    }]
                }]
            }
        }]
    }
}

--
The library and the classroom
--
Gets the resource list of a course
GET /courses/{idc}/resources/
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }

Links a resource to a course
POST /courses/{idc}/resources/{idr}
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }

Unlinks a resource from a course
DELETE /courses/{idc}/resources/{idr}
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }

Gets the list of resources of a classroom
GET /classrooms/{idk}/resources/
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }

Links a resource to a classroom
POST /classrooms/{idk}/resources/{idr}
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }

Unlinks a resource from a classroom
DELETE /classrooms/{idk}/resources/{idr}
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }

Creates a new resource
POST /resources
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }

Gets the resource metadata
GET /resources/{idr}
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }

Gets a filtered list of resources
GET /resources/{?filter}
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }

Deletes a resource
DELETE /resources/{idr}
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }
